- name: Update APT packages across sofia-cluster
  hosts: all
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
        upgrade: yes

    - name: Upgrade APT packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Check if system reboot is required
      stat: 
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the system
      reboot:
        reboot_timeout: 300
      when: reboot_required.stat.exists